name: Auto Commit Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at midnight (UTC)
  workflow_dispatch:     # Manually trigger karne ka option bhi hoga

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto Commit
        run: |
          date > last-updated.txt
          git config --global user.name "muhammadasif46"
          git config --global user.email "asifahmed32c@gmail.com"
          git add .
          git commit -m "Automated commit - $(date)"
          git push
